# Proxy API requests to https://dentech-api.onrender.com
[[redirects]]
  from = "/api/*"
  to = "https://dentech-api.onrender.com/:splat"
  status = 200
  force = true

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200